sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: cdcU4tBe175hlgrc314dQE37qwn4mxaaEsfmEmn+aR0LaXAJankh4X1vFB/Z8hmgCNjrXuvl1k5CNq2kR/eXSZlJ4UPtx9xuwdCJGfxN2xgBT2HuUe8o/l0q63is8F1baSt9tdenTc17vvvLaBdrtNISbhtI+V2GGzIZuZCZPeW205E/MuaP+k0jyjvQcSp/OUBw+Fou0LtHoGX61CQ9LXIRqbXLfRhPGxUmECIOAbWXIUF61UdT2iv9ONtq3glCH5BzoJAlob5DVPOVYGHmixo2O2Llxj8pEec+5bChhqxy8sU6eVGVN1eyiQEBvDwGT/Z8RbtZKuzkZTy49NaS9sA2+GNOaQoCo7Eo7lPXaDVR0WG2W6hpeFiChckjvNtc/8RoYO+RXkclhPJSUCwpKoDMaXWZ1C4lSAHOHEaNdSdzj8QpZxCh3V0bRvTTfkeoBhW0mwKOvuw4uw5R2GcGKYhi88E0sOwI5lcJs/3qTc9355r6sdzn4L2VEk72mKCSLFNqhJhgCZWKQzh3KYvTEOn6k2oqlQ+BlLSP+0CyhFlPmasGHtrkZA3pi3V2glEcZ6q9diMNCRZhoxFjhzCJ/xNcQilqdx2XqT/TCCW+8rlz82Tu/mO+qbtIFkL9QRqBmCgSUpsV4POuY0L1ZvilkwLjCWT1fGYgLG0hX5BBS1M=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: C9Q3eqBgjcsRtrh8dI7xK0ry/CGNYERIF9hwAdfsrIN+YFuTa4pB7trpKLnHLAzr9gM2e3Z7j2jqqTfHk+x4zwX5ylSmsRGf8OQnjTx3O8tjvBdWWQduPLVPG9gjcY+KAlK2c7dJZqH/2csaR/5BrlMr4aYzS3KkFpAqdyw+aXiM0iIn0AwrYPpylUZyQedufTFx7pP1T6us/sbig6NO/rcIyRkJMx6lwDTOuurZRrMk+MxpV9yn34uMZzeA332EX7Ozb8ySeEmyutnhOmoHALpo6gyXMh1kZjR1Pvv9giiZ0TPYwA+HPXlNxXszT4DhOT9wPFSoeX9GY66OnUeSMHeSyL9wziTYKwrowEH8v8QyNXor0EYPJxQ4aGeSiWvB1Xd7Znwvh2LPN/oOhBiOKCw7rqgxg+QCehyHWyO2NKn/ZjxKK6Hiqg1zlC9K3lYi+lFtiTijWZ6R/e6pf9z8IE9Hnie3pWI2OS72UQzfHFqrBD4OhZvLUzVSZHQZjfiDEQNGU8kJLiBUBo0xBh3lF8jiFsxVfibEYSrbNih6OvDzQT6ixlS8lgILFLuxp+0ZIdgdHSVFGEHr8iKq9fNVhk7q4F3Ow4oPAmF/gAwolO4d3U8EJ41iKYegJSk+vBphoJeYwq465EmhXLnIW5Q9u75bu6nDK2yd6N/7DsiyOJA=
